context("getdata_paleomap")
test_that("tests on getdata_paleomap which should return a data.frame with at least paleolat, paleolng, taxon_name and taxon_rank", {
  data<-  getdata_paleomap("Quaternary")
  expect_true(is.data.frame(data))
  expect_true(grep("paleolat", names(data))!=0)
  expect_true(grep("paleolng", names(data))!=0)
  expect_true(grep("taxon_name", names(data))!=0)
  expect_true(grep("taxon_rank", names(data))!=0)
  minlat <- min(data$paleolat)
  expect_true(minlat>=-90)
  maxlat <- max(data$paleolat)
  expect_true(maxlat<=90)
  minlng <- min(data$paleolng)
  expect_true(minlng>=-180)
  maxlng <- max(data$pleolng)
  expect_true(maxlng<=180)
})